export interface Iservicios {
    IdServicio?:number| null,
    Nombre?:string| null,
    IdEspecialidad:string|null,
    IdTipoServicio?:string| null,
    Codigo?:string| null,
    SVG?:string| null,
    IdProducto?:string| null,
    soloTipoSexo?:string| null,
    maximaEdad?:string| null,
    codigoServicioSEM?:string| null,
    ubicacionSEM?:string| null,
    codigoServicioHIS?:string| null,
    costoCeroCE?:string| null,
    MinimaEdad?:string| null,
    idEstado?:string| null,
    Triaje?:string| null,
    EsObservacionEmergencia?:string| null,
    UsaModuloNinoSano?:string| null,
    UsaModuloMaterno?:string| null,
    UsaGalenHos?:string| null,
    TipoEdad?:string| null,
    UsaFUA?:string| null,
    codigoServicioSuSalud?:string| null,
    codigoServicioFUA?:string| null,
}
